# Generated by Django 2.1.5 on 2019-03-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
