# Generated by Django 2.1.7 on 2019-03-26 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0004_note_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='users',
            field=models.ManyToManyField(related_name='shared_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
